FROM java:8

VOLUME /tmp
ADD demo-docker.jar /opt/demo-docker/
EXPOSE 8087
WORKDIR /opt/demo-docker/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "demo-docker.jar"]
