
---
spring:
  profiles: dev
  thymeleaf.cache: false
  application:
    name: demo-docker

server:
  port: 8080




---
spring:
  profiles: test
  thymeleaf.cache: false
  application:
    name: demo-docker

server:
  port: 8081
