
---
spring:
  profiles: dev
  thymeleaf.cache: false
  application:
    name: demo-docker

server:
  port: 8080





---
spring:
  profiles: test
  thymeleaf.cache: false
  application:
    name: demo-docker

server:
  port: 8081

redis:
  host: 127.0.0.1
  port: 6379
  database: 0
  password:
#  sentinel:
#    master: mymaster
#    nodes: 10.30.95.85:26379
  pool:
    max-active: -1
    max-wait: -1
    max-idle: 8
    min-idle: 0
  timeout: 10000
